/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import modelo.ConsultasSQL;
import modelo.Modelo;
import modelo.Productos;

/**
 *
 * @author julio
 */
public class FrmProducto extends javax.swing.JFrame {

    Productos pr= new Productos();
    ConsultasSQL sql= new ConsultasSQL();
    Modelo mod= new Modelo();
    public FrmProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_insertar = new javax.swing.JButton();
        btn_mostrar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_proveedor = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_precioVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        cbx_categoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbx_proveedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("PrecioCompra");

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("descripcion");

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("nombre");

        jLabel6.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Proveedor");

        btn_insertar.setBackground(new java.awt.Color(255, 255, 0));
        btn_insertar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_insertar.setText("insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        btn_mostrar.setBackground(new java.awt.Color(255, 255, 0));
        btn_mostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_mostrar.setText("mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(255, 255, 0));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_actualizar.setText("actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        TABLA.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        TABLA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA);

        txt_id.setEditable(false);
        txt_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_idMouseEntered(evt);
            }
        });
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("stock");

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("CODIGO");

        txt_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigoFocusLost(evt);
            }
        });

        cbx_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_categoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbx_categoriaMouseEntered(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("fabricante");

        cbx_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_proveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbx_proveedorMouseEntered(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbx_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(50, 50, 50)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbx_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_actualizar)
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbx_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbx_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txt_precioVenta))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
    Conexion cin = new Conexion();
          Connection cnx=cin.conectar();
          String sql="insert into productos1(id,nombre,descripcion,proveedor,stock,precio,precioCompra,idProveedor,categoria,codigo)values(?,?,?,?,?,?,?,?,?,?)";
          
          try{
              PreparedStatement pst=cnx.prepareStatement(sql);
              if (txt_nombre.getText().isEmpty()||txt_nombre.getText().isEmpty()||txt_descripcion.getText().isEmpty()||txt_proveedor.getText().isEmpty()||
                      txt_stock.getText().isEmpty()||txt_precio.getText().isEmpty()||txt_precioVenta.getText().isEmpty()||txt_codigo.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"debes de llenar todos los campos ","mensaje error",JOptionPane.ERROR_MESSAGE);
              }else{
                 
                    pst.setString(1, this.txt_id.getText());
              pst.setString(2, this.txt_nombre.getText());
              pst.setString(3, this.txt_descripcion.getText());
              pst.setString(4, this.txt_proveedor.getText());
              pst.setString(5, this.txt_stock.getText());
              pst.setString(6, this.txt_precio.getText());
              pst.setString(7, this.txt_precioVenta.getText());
              pst.setString(8, this.cbx_proveedor.getSelectedItem().toString());
               pst.setString(9, this.cbx_categoria.getSelectedItem().toString());
               pst.setString(10,this.txt_codigo.getText());
              }
               int select=pst.executeUpdate();
               if (select>0) {
                  JOptionPane.showMessageDialog(null, "datos ingresados correctamente");
                  limpiar();
              }else{
                   JOptionPane.showMessageDialog(null, "ingrese todos los campos ","mensaje error",JOptionPane.ERROR_MESSAGE);
               }
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
          
    }//GEN-LAST:event_btn_insertarActionPerformed
public void mostrar(){
    DefaultTableModel model= new DefaultTableModel();
    String titulos[] ={"id","nombre","descripcion","proveedor","stock","precio","precio Venta","fabricante","categoria","codigo"};
    model.setColumnIdentifiers(titulos);
    Conexion cn = new Conexion();
    Connection cnx=cn.conectar();
    String sql="select productos1.id,productos1.nombre,productos1.descripcion,productos1.proveedor,productos1.stock,productos1.precio,productos1.precioCompra,proveedores.nombre,"
            + "categoria.categoria ,productos1.codigo from productos1 inner join proveedores on proveedores.idproveedor=productos1.idproveedor inner join categoria on categoria.idcategoria"
            + "=productos1.categoria group by id";
    try{
        Statement st=cnx.createStatement();
        ResultSet rs=st.executeQuery(sql);
        String numeros []= new String[10];
        while (rs.next()) {
             numeros[0]=rs.getString("id");
            numeros[1]=rs.getString("nombre");
             numeros[2]=rs.getString("descripcion");
              numeros[3]=rs.getString("proveedor");
               numeros[4]=rs.getString("stock");
                numeros[5]=rs.getString("precio");
                 numeros[6]=rs.getString("precioCompra");
                  numeros[7]=rs.getString("proveedores.nombre");
                   numeros[8]=rs.getString("categoria");
                    numeros[9]=rs.getString("codigo");
                    model.addRow(numeros);
                    this.TABLA.setModel(model);
        }
        cnx.close();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    
}
public void eliminar(){
    Conexion cn = new Conexion ();
    Connection cnx=cn.conectar();
    int selecciona=this.TABLA.getSelectedRow();
    String sel=this.TABLA.getValueAt(selecciona, 0).toString();
    String sql="delete from productos1 where id="+sel;
    try{
        PreparedStatement pst=cnx.prepareStatement(sql);
        if ( pst.execute()) {
             JOptionPane.showMessageDialog(null, "datos eliminados correctamente");
        }
       cnx.close();
       
    }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
    }
    
}
    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        mostrar();
        
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
      Conexion cn = new Conexion ();
    Connection cnx=cn.conectar();
   
    String sql="update productos1 set nombre='"+this.txt_nombre.getText()+"',descripcion='"+this.txt_descripcion.getText()+"',proveedor='"+
            this.txt_proveedor.getText()+"',stock='"+this.txt_stock.getText()+"',precio='"+txt_precioVenta.getText()+"',precioCompra='"+this.txt_precio.getText()
            +"',idproveedor='"+this.cbx_proveedor.getSelectedItem()+"',categoria='"+this.cbx_categoria.getSelectedItem()+"',codigo='"+this.txt_codigo.getText()
            +"' where id="+this.txt_id.getText();
    try{
        PreparedStatement pst=cnx.prepareStatement(sql);
        if ( pst.execute()) {
             JOptionPane.showMessageDialog(null, "datos actualiuzados  correctamente");
             limpiar();
        }
       cnx.close();
       
    }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_idMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_idMouseEntered
       int in=0;
           ArrayList<Integer> numeros= new ArrayList<>();
           Conexion con = new Conexion();
            try {
            Connection conexion =con.conectar();
            PreparedStatement pst1 =conexion.prepareStatement("select id from productos1");
            ResultSet rs1 =pst1.executeQuery();
           
               while (rs1.next()) {
                   numeros.add(Integer.parseInt(rs1.getString("id")));
                   
                }
                
                 in =numeros.size()+5;
                limpiar();
           
        } catch (Exception ex) {
           
        }
       String identificador=String.valueOf(in);
                 this.txt_id.setText(identificador);
                this.txt_id.setEditable(false);
    }//GEN-LAST:event_txt_idMouseEntered

    private void cbx_proveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_proveedorMouseEntered
       Conexion con = new Conexion();
       Connection cnx=con.conectar();
       String sql="select idproveedor from proveedores";
       try{
           Statement st =cnx.createStatement();
           ResultSet rs =st.executeQuery(sql);
           String numero[]= new String[1];
          
          
           while (rs.next()) {
              this.cbx_proveedor.addItem(rs.getString("idproveedor"));
           }
           cnx.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_cbx_proveedorMouseEntered

    private void cbx_categoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_categoriaMouseEntered
           Conexion con = new Conexion();
       Connection cnx=con.conectar();
       String sql="select idcategoria from categoria";
       try{
           Statement st =cnx.createStatement();
           ResultSet rs =st.executeQuery(sql);
           String numero[]= new String[1];
          
          
           while (rs.next()) {
             this.cbx_categoria.addItem(rs.getString("idcategoria"));
              
           }
           cnx.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
     
    }//GEN-LAST:event_cbx_categoriaMouseEntered
     private void limpiar(){
         
          this.txt_id.setText("");
              this.txt_nombre.setText("");
              this.txt_descripcion.setText("");
             this.txt_proveedor.setText("");
             this.txt_stock.setText("");
              this.txt_precio.setText("");
              this.txt_precioVenta.setText("");
              this.cbx_proveedor.getSelectedItem().toString();
               this.cbx_categoria.getSelectedItem().toString();
              this.txt_codigo.setText("");       
     }
    private void cbx_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_categoriaMouseClicked
        String del=cbx_categoria.getSelectedItem().toString();
        int seleccion=Integer.parseInt(del);
         Conexion con = new Conexion();
       Connection cnx=con.conectar();
       String sql="select categoria from categoria where idcategoria="+seleccion;
           try{
           Statement st =cnx.createStatement();
           ResultSet rs =st.executeQuery(sql);
           String numero[]= new String[1];
          
          
           while (rs.next()) {
            
              numero[0]=rs.getString("categoria");
              JOptionPane.showMessageDialog(null,"categoria= "+numero[0],"mensaje", JOptionPane.INFORMATION_MESSAGE);
           }
           
           cnx.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
        
    }//GEN-LAST:event_cbx_categoriaMouseClicked

    private void cbx_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_proveedorMouseClicked
        String del=this.cbx_proveedor.getSelectedItem().toString();
        int seleccion=Integer.parseInt(del);
         Conexion con = new Conexion();
       Connection cnx=con.conectar();
       String sql="select nombre from proveedores where idproveedor="+seleccion;
           try{
           Statement st =cnx.createStatement();
           ResultSet rs =st.executeQuery(sql);
           String numero[]= new String[1];
          
          
           while (rs.next()) {
            
              numero[0]=rs.getString("nombre");
              JOptionPane.showMessageDialog(null,"proveedor= "+numero[0],"mensaje", JOptionPane.INFORMATION_MESSAGE);
           }
           
           cnx.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_cbx_proveedorMouseClicked

    private void txt_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusLost
                 String codigo=this.txt_codigo.getText();
             Conexion con = new Conexion();
       Connection cnx=con.conectar();
       String sql="select codigo  from productos1 where codigo="+codigo;
       try{
           Statement st =cnx.createStatement();
           ResultSet rs =st.executeQuery(sql);
           String numero[]= new String[1];
          
          
           while (rs.next()) {
             
              numero[0]=rs.getString("codigo");
              JOptionPane.showMessageDialog(null,"el codigo de producto  ya existe en la base de datos "+numero[0]);
              this.txt_codigo.setText("");
           }
           cnx.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "debe ingresar un codigo ");
       }
    }//GEN-LAST:event_txt_codigoFocusLost

    private void TABLAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLAMouseClicked
      int codigo = this.TABLA.getSelectedRow();
      String id=this.TABLA.getValueAt(codigo,0).toString();
      String code=this.TABLA.getValueAt(codigo,9).toString();
      String nombre=this.TABLA.getValueAt(codigo,1).toString();
      String descripcion=this.TABLA.getValueAt(codigo,2).toString();
      String proveedor=this.TABLA.getValueAt(codigo,3).toString();
      String fabricante=this.TABLA.getValueAt(codigo,0).toString();
      String categoria=this.TABLA.getValueAt(codigo,0).toString();
      String stock=this.TABLA.getValueAt(codigo,4).toString();
      String precio=this.TABLA.getValueAt(codigo,6).toString();
        if (precio.isEmpty()) {
            precio="0";
        }
      String precioVenta=this.TABLA.getValueAt(codigo,5).toString();
      
        this.txt_codigo.setText(code);
        this.txt_id.setText(id);
        this.txt_nombre.setText(nombre);
        this.txt_descripcion.setText(descripcion);
        this.txt_proveedor.setText(proveedor);
        this.txt_stock.setText(stock);
        
           this.txt_precio.setText(precio); 
        
        
        
        this.txt_precioVenta.setText(precioVenta);
        
        
        
        JOptionPane.showMessageDialog(null,"opciones de tabla  "+id);
    }//GEN-LAST:event_TABLAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TABLA;
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_insertar;
    public javax.swing.JButton btn_mostrar;
    public javax.swing.JComboBox<String> cbx_categoria;
    private javax.swing.JComboBox<String> cbx_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_descripcion;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_precio;
    public javax.swing.JTextField txt_precioVenta;
    public javax.swing.JTextField txt_proveedor;
    public javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
