/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlProductos;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("principal");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        m_itemCerrarSesion = new javax.swing.JMenuItem();
        m_item_salir = new javax.swing.JMenuItem();
        menu_almacen = new javax.swing.JMenu();
        item_producto = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menu_compras = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        item_proveedor = new javax.swing.JMenuItem();
        menu_ventas = new javax.swing.JMenu();
        item_venta = new javax.swing.JMenuItem();
        item_verificarProducto = new javax.swing.JMenuItem();
        item_cliente = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        item_ventasRealizadas = new javax.swing.JMenuItem();
        item_ventasDetalladas = new javax.swing.JMenuItem();
        estadistica_mensual = new javax.swing.JMenuItem();
        item_comprasRealizadas = new javax.swing.JMenuItem();
        item_comprasDetalladas = new javax.swing.JMenuItem();
        menu_mantenimiento = new javax.swing.JMenu();
        item_empleado = new javax.swing.JMenuItem();
        item_tipoDocumento = new javax.swing.JMenuItem();
        item_tipoUsuario = new javax.swing.JMenuItem();
        menu_cancelaciones = new javax.swing.JMenu();
        item_cancelaCompra = new javax.swing.JMenuItem();
        item_cancelaVenta = new javax.swing.JMenuItem();
        menu_herramientas = new javax.swing.JMenu();
        item_contraseña = new javax.swing.JMenuItem();
        item_calculadora = new javax.swing.JMenuItem();
        item_respaldoBD = new javax.swing.JMenuItem();
        item_restaurarBD = new javax.swing.JMenuItem();
        menu_ayuda = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        menu_archivo.setForeground(new java.awt.Color(51, 51, 51));
        menu_archivo.setText("archivo");

        m_itemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        m_itemCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/salir_1.png"))); // NOI18N
        m_itemCerrarSesion.setText("cerrar sesion");
        m_itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_itemCerrarSesionActionPerformed(evt);
            }
        });
        menu_archivo.add(m_itemCerrarSesion);

        m_item_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        m_item_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/eliminar.png"))); // NOI18N
        m_item_salir.setText("cerrar aplicacion");
        m_item_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_item_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(m_item_salir);

        jMenuBar1.add(menu_archivo);

        menu_almacen.setText("almacen");

        item_producto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        item_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/producto.png"))); // NOI18N
        item_producto.setText("producto");
        item_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_productoActionPerformed(evt);
            }
        });
        menu_almacen.add(item_producto);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/lupa.png"))); // NOI18N
        jMenuItem5.setText("categoria");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu_almacen.add(jMenuItem5);

        jMenuBar1.add(menu_almacen);

        menu_compras.setText("compras");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/Carrito-de-compras.png"))); // NOI18N
        jMenuItem6.setText("compra");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_compras.add(jMenuItem6);

        item_proveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        item_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/proveedor.png"))); // NOI18N
        item_proveedor.setText("proveedor");
        item_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_proveedorActionPerformed(evt);
            }
        });
        menu_compras.add(item_proveedor);

        jMenuBar1.add(menu_compras);

        menu_ventas.setText("ventas");

        item_venta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_CONTROL, 0));
        item_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/Nventa.png"))); // NOI18N
        item_venta.setText("venta");
        item_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ventaActionPerformed(evt);
            }
        });
        menu_ventas.add(item_venta);

        item_verificarProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        item_verificarProducto.setText("verificar producto");
        item_verificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_verificarProductoActionPerformed(evt);
            }
        });
        menu_ventas.add(item_verificarProducto);

        item_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        item_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/Clientes.png"))); // NOI18N
        item_cliente.setText("cliente");
        item_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_clienteActionPerformed(evt);
            }
        });
        menu_ventas.add(item_cliente);

        jMenuBar1.add(menu_ventas);

        menu_consultas.setText("consultas");

        item_ventasRealizadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        item_ventasRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/money.png"))); // NOI18N
        item_ventasRealizadas.setText("ventas realizadas");
        menu_consultas.add(item_ventasRealizadas);

        item_ventasDetalladas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        item_ventasDetalladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/report.png"))); // NOI18N
        item_ventasDetalladas.setText("ventas detalladas");
        menu_consultas.add(item_ventasDetalladas);

        estadistica_mensual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_TAB, java.awt.event.InputEvent.ALT_MASK));
        estadistica_mensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/torta.png"))); // NOI18N
        estadistica_mensual.setText("estadistica mensual");
        menu_consultas.add(estadistica_mensual);

        item_comprasRealizadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        item_comprasRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/compras.png"))); // NOI18N
        item_comprasRealizadas.setText("compras realizadas");
        menu_consultas.add(item_comprasRealizadas);

        item_comprasDetalladas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.CTRL_MASK));
        item_comprasDetalladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/Carrito-de-compras.png"))); // NOI18N
        item_comprasDetalladas.setText("compras detalladas ");
        menu_consultas.add(item_comprasDetalladas);

        jMenuBar1.add(menu_consultas);

        menu_mantenimiento.setText("mantenimiento");

        item_empleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        item_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/Clientes.png"))); // NOI18N
        item_empleado.setText("empleado");
        item_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_empleadoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(item_empleado);

        item_tipoDocumento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        item_tipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/excel.png"))); // NOI18N
        item_tipoDocumento.setText("tipo documento");
        menu_mantenimiento.add(item_tipoDocumento);

        item_tipoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        item_tipoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/proveedor.png"))); // NOI18N
        item_tipoUsuario.setText("tipo usuario");
        item_tipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_tipoUsuarioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(item_tipoUsuario);

        jMenuBar1.add(menu_mantenimiento);

        menu_cancelaciones.setText("cancelaciones");

        item_cancelaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/borrar.png"))); // NOI18N
        item_cancelaCompra.setText("cancelar compra");
        menu_cancelaciones.add(item_cancelaCompra);

        item_cancelaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/eliminar.png"))); // NOI18N
        item_cancelaVenta.setText("cancelar venta");
        menu_cancelaciones.add(item_cancelaVenta);

        jMenuBar1.add(menu_cancelaciones);

        menu_herramientas.setText("herramientas");

        item_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/Actualizar (2).png"))); // NOI18N
        item_contraseña.setText("cambiar contraseña");
        item_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_contraseñaActionPerformed(evt);
            }
        });
        menu_herramientas.add(item_contraseña);

        item_calculadora.setText("calculadora");
        item_calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_calculadoraActionPerformed(evt);
            }
        });
        menu_herramientas.add(item_calculadora);

        item_respaldoBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/GuardarTodo.png"))); // NOI18N
        item_respaldoBD.setText("respaldar BD");
        menu_herramientas.add(item_respaldoBD);

        item_restaurarBD.setText("restaurar BD");
        menu_herramientas.add(item_restaurarBD);

        jMenuBar1.add(menu_herramientas);

        menu_ayuda.setText("ayuda");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img/ayuda.png"))); // NOI18N
        menu_ayuda.add(jMenu3);

        jMenuBar1.add(menu_ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_tipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_tipoUsuarioActionPerformed
       
    }//GEN-LAST:event_item_tipoUsuarioActionPerformed

    private void item_calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_calculadoraActionPerformed
FrCalculadora calcu= new FrCalculadora();   
calcu.setVisible(true);
    }//GEN-LAST:event_item_calculadoraActionPerformed

    private void m_item_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_item_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_m_item_salirActionPerformed

    private void m_itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_itemCerrarSesionActionPerformed
    this.setVisible(false);
    new Login().setVisible(true);
    }//GEN-LAST:event_m_itemCerrarSesionActionPerformed

    private void item_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ventaActionPerformed
     Ventas vta= new Ventas();
     vta.setVisible(true);
    
    }//GEN-LAST:event_item_ventaActionPerformed

    private void item_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_contraseñaActionPerformed
     Contraseña contr= new Contraseña();
     contr.setVisible(true);
      
    
    }//GEN-LAST:event_item_contraseñaActionPerformed

    private void item_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_productoActionPerformed
       FrmProducto product= new FrmProducto();
       product.setVisible(true);
    //   CtrlProductos pro= new CtrlProductos(Producto pr,FrmProducto fPr,Modelo mod);
    }//GEN-LAST:event_item_productoActionPerformed

    private void item_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_empleadoActionPerformed
   
        new Usuarios().setVisible(true);
       
    }//GEN-LAST:event_item_empleadoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
new Compra().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void item_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_clienteActionPerformed
        new Clientes().setVisible(true);
    }//GEN-LAST:event_item_clienteActionPerformed

    private void item_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_proveedorActionPerformed
        new proveedores().setVisible(true);
    }//GEN-LAST:event_item_proveedorActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
                new Categoria().setVisible(true);                                                                 //categoria
                                                                                 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void item_verificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_verificarProductoActionPerformed
       new Verificar_producto().setVisible(true);
    }//GEN-LAST:event_item_verificarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem estadistica_mensual;
    public javax.swing.JMenuItem item_calculadora;
    public javax.swing.JMenuItem item_cancelaCompra;
    public javax.swing.JMenuItem item_cancelaVenta;
    public javax.swing.JMenuItem item_cliente;
    public javax.swing.JMenuItem item_comprasDetalladas;
    public javax.swing.JMenuItem item_comprasRealizadas;
    public javax.swing.JMenuItem item_contraseña;
    public javax.swing.JMenuItem item_empleado;
    public javax.swing.JMenuItem item_producto;
    public javax.swing.JMenuItem item_proveedor;
    public javax.swing.JMenuItem item_respaldoBD;
    public javax.swing.JMenuItem item_restaurarBD;
    public javax.swing.JMenuItem item_tipoDocumento;
    public javax.swing.JMenuItem item_tipoUsuario;
    public javax.swing.JMenuItem item_venta;
    public javax.swing.JMenuItem item_ventasDetalladas;
    public javax.swing.JMenuItem item_ventasRealizadas;
    public javax.swing.JMenuItem item_verificarProducto;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem5;
    public javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuItem m_itemCerrarSesion;
    public javax.swing.JMenuItem m_item_salir;
    public javax.swing.JMenu menu_almacen;
    public javax.swing.JMenu menu_archivo;
    public javax.swing.JMenu menu_ayuda;
    public javax.swing.JMenu menu_cancelaciones;
    public javax.swing.JMenu menu_compras;
    public javax.swing.JMenu menu_consultas;
    public javax.swing.JMenu menu_herramientas;
    public javax.swing.JMenu menu_mantenimiento;
    public javax.swing.JMenu menu_ventas;
    // End of variables declaration//GEN-END:variables
}
